### ISSUE TITLE
FDR calculation: ZeroDivisionError: division by zero 

### ISSUE THREAD

**Issue by husensofteng** [lehtiolab/proteogenomics-analysis-workflow#5]
I get the following error when manually running the [svmToTSV](https://github.com/lehtiolab/proteogenomics-analysis-workflow/blob/4dc56b0b7e4306888bda0dc7108a71fda7f11f44/ipaw.nf#L511) script, It is related to the number of decoys with the given svm score:
Command error:
      psms[psm[0]] = {'decoy': pdecoy, 'svm': psm[1], 'qval': decoys[True]/decoys[False]}  # T-TDC
  ZeroDivisionError: division by zero

Command output (Manual) of print(psm[1], decoys) is 0.867, {True: 1, False: 0} since there is no decoy for this svm score the devision is by zero.

An option is setting the FDR to 0.0 in such cases.

**Comment by glormph** [comment]
It's actually opposite, there are no target scores. Catching this exception would instead set the FDR to 1.0. Sounds like a good idea!

**Comment by husensofteng** [comment]
yeah, you are right, I read it the opposite. I will make a request.

**Comment by glormph** [comment]
Fixed with #6
